module.exports = {
  docs: [
    {
      type:'doc',
      id: 'index',
    },
    {
      type: 'category',
      label: 'Database',
      items: [
        'db/MongoDB',
        'db/MySQL',
        'db/PostgreSQL',
        'db/Redis'
      ],
    },
    {
      type: 'category',
      label: 'Editor / Shell',
      items: [
        'editors/custom',
        'editors/atom',
        'editors/bash',
        'editors/git',
        'editors/phpstorm',
        'editors/sublime',
        'editors/subversion',
        'editors/terminal',
        'editors/textmate',
        'editors/unix',
        'editors/vi',
        'editors/zsh',
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      items: [
        'waf/nodejs',
        'waf/npm',
        'waf/rails',
        'waf/react',
        'waf/react_native',
        'waf/vue',
      ],
    },
    {
      type: 'category',
      label: 'Language',
      items: [
        'lang/Golang',
        'lang/GraphQL',
        'lang/JavaScript',
        'lang/PHP',
        'lang/Python',
        'lang/Ruby',
        'lang/Rust',
      ],
    },
    {
      type: 'category',
      label: 'Localhost',
      items: [
        'localhost/macs',
        'localhost/apple',
        'localhost/chrome',
        'localhost/brew',
        'localhost/adobe',
        'localhost/sketch',
        'localhost/ngrok',
      ],
    },
    {
      type: 'category',
      label: 'Projects',
      items: [
        'projects/dw',
        'projects/gzet',
        'projects/juryd',
        'projects/pants',
        'projects/woozer',
        'projects/zeke',
        'projects/zw',
      ],
    },
    {
      type: 'category',
      label: 'Remote',
      items: [
        'host/Discourse',
        'host/Drupal',
        'host/Gitea',
        'host/Gogs',
        'host/Icecast',
        'host/InvoicePlane',
        'host/Laravel',
        'host/Lychee',
        'host/Mailcow',
        'host/Nodebb',
        'host/Phproject',
        'host/Piwik',
        'host/Siege-sproxy',
        'host/Webmin',
        'host/WordPress',
        'host/Zammad',
      ],
    },
    {
      type: 'category',
      label: 'SasS',
      items: [
        'saas/aws',
        'saas/google',
        'saas/heroku',
        'saas/linode',
        'saas/now',
        'saas/stripe',
        'saas/twilio',
      ],
    },
    {
      type: 'category',
      label: 'Server',
      items: [
        'server/apache',
        'server/docker',
        'server/goaccess',
        'server/htop',
        'server/iptables',
        'server/kubernetes',
        'server/letsencrypt',
        'server/lynis',
        'server/mail',
        'server/monit',
        'server/nginx',
        'server/ubuntu',
        'server/ufw',
      ],
    },
  ],
};
